name: helathcareapp
description: "the healthcare management app uder PT Abadi Smilynks"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dots_indicator: ^3.0.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  flutter_bloc: ^8.1.3
  http: ^1.1.2
  path: ^1.8.3
  google_fonts: ^6.1.0
  nil: ^1.1.1
  intl: '>=0.17.0-nullsafety.2 <0.19.0'
  local_auth: ^2.1.8
  local_auth_ios: ^1.0.12
  package_info: ^2.0.2
  package_info_plus: ^5.0.1
  path_provider: ^2.1.2
  qr: ^3.0.1
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  permission_handler: ^11.1.0
  flutter_image_slideshow: ^0.1.6
  page_transition: ^2.1.0
  flutter_plugin_android_lifecycle: ^2.0.0
#  camera: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - asset/smilynks.png
    - asset/alarm.png
    - asset/happy.png
    - asset/talking.png
    - asset/inpatients.jpg
    - asset/google-logo.png
    - asset/apple-logo.png
    - asset/whatsapp-logo.png
    - asset/contact-form.png
    - asset/open-book.png
    - asset/info.png
    - asset/id-card.png
    - asset/247-services.png
    - asset/benefits.png
    - asset/hospital-building.png
    - asset/insurance-policy.png
    - asset/hospital.png
    - asset/employee.png
    - asset/identification.png
    - asset/health-insurance.png
    - asset/healthcare.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
